### ISSUE TITLE
A tradução está apenas nas interfaces. 

### ISSUE THREAD

**Issue by tadeg3** [WeslleyNasRocha/cultist-simulator-pt-br#44]
Prezados boa tarde , eu estou tentando usar a tradução mas a mesma está apenas nos menus .  Já existem outros reports lá nos comentários , caso esteja repetido este relato peço que desconsiderem e caso haja uma solução por gentileza me informar. Ótimo trabalho com a tradução e muito obrigado! . 
![Captura de tela 2022-06-07 120947](https://user-images.githubusercontent.com/107059119/172415921-46e14126-d503-4447-8b72-e4af52311f1b.png)

**Comment by tadeg3** [comment]
Agradeço pelo retorno, espero que consiga atualizar eu to loco pra jogar !  caso não consiga atualizar  se puder me ajudar a usar a tradução de outra forma eu agradeço demais ! Bom trabalho ! vlw!

**Comment by WeslleyNasRocha** [comment]
Vlww, eu consegui fazer funcionar de novo, da uma atualizada lá na steam que já deve ta lá

**Comment by tadeg3** [comment]
eu agradeço demais pela ajuda!  tmj
